version: '3.8'
services:
  dev-intership-db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sushil0722
      - POSTGRES_DB=nestjs
    ports:
      - 5438:5432
    # environment:
    #   MYSQL_ROOT_PASSWORD: sushil0722
    #   MYSQL_DATABASE: nestjs
    #   # MYSQL_USER: root
    #   #  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    #   #  MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    #   MYSQL_PASSWORD: sushil0722
    # ports:
    #   - 3308:3306
    networks:
      - sushil-networks
networks:
  sushil-networks:
